[package]
name = "dotnet-bindgen-core"
version = "0.1.0"
authors = ["Joe Roberts <joe@jwjr.co.uk>"]
edition = "2018"

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full", "fold"] }
proc-macro2 = "1.0"
