[package]
name = "test-lib"
version = "0.1.0"
authors = ["Joe Roberts <joe@jwjr.co.uk>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
dotnet-bindgen-core = { path = "../dotnet-bindgen-core" }
dotnet-bindgen = { path = "../../" }