[package]
name = "dotnet-bindgen-cli"
version = "0.1.0"
authors = ["Joe Roberts <joe@jwjr.co.uk>"]
edition = "2018"

[dependencies]
dotnet-bindgen-core = { path = "../dotnet-bindgen-core" }
dotnet-bindgen = { path = "../../" }
goblin = "0.0.24"
heck = "0.3"
clap = "2.33"
libloading = "0.5"