[package]
name = "dotnet-bindgen-cli"
version = "0.1.0"
authors = ["Joe Roberts <joe@jwjr.co.uk>"]
edition = "2018"

[dependencies]
dotnet-bindgen-core = { path = "../dotnet-bindgen-core" }
goblin = "0.0.24"
syn = "1"
