[package]
name = "test_lib"
version = "0.1.0"
authors = ["Joe Roberts <joe@jwjr.co.uk>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
dotnet_bindgen_core = { path = "../dotnet_bindgen_core" }
dotnet-bindgen-macro = { path = "../macro" }
