[package]
name = "dotnet-bindgen-macro"
version = "0.1.0"
authors = ["Joe Roberts <joe@jwjr.co.uk>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
dotnet-bindgen-macro-support = { path = "../macro-support" }
proc-macro2 = "1.0.28"
quote = "1.0.9"
